main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /BonsPlans

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

