<?php

namespace MainBundle\Repository;

/**
 * DemandeAjoutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeAjoutRepository extends \Doctrine\ORM\EntityRepository
{
}
