<?php

namespace MainBundle\Repository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function FiltrerDQL($critere)
    {
        $query=$this->getEntityManager()->createQuery("SELECT e FROM MainBundle:Etablissement e WHERE e.type like :typ 
            order by e.nom ASC")
            ->setParameter('typ', '%'.$critere.'%');
        return $query->getResult();
    }

    public function RechercherDQL($nom)
    {
        $query=$this->getEntityManager()->createQuery("SELECT et FROM MainBundle:Etablissement et WHERE et.nom like :no 
            order by et.nom ASC")
            ->setParameter('no', '%'.$nom.'%');
        return $query->getResult();
    }

    public function RechercherCNDQL($nom,$critere)
    {
        $query=$this->getEntityManager()->createQuery("SELECT et FROM MainBundle:Etablissement et WHERE et.nom like :no and et.type like :typ
            order by et.nom ASC")
            ->setParameter('no', '%'.$nom.'%')->setParameter('typ','%'.$critere.'%');
        return $query->getResult();
    }

    public function RechercherT($tag)
    {
        $SQB1 = $this->getEntityManager()->createQueryBuilder()->select('et')->from("MainBundle:Etablissement",'et')
            ->join('et.tags','et_tags')->where('et_tags.name=:t')->setParameter('t',$tag);
        return $SQB1->getQuery()->getResult();
    }
    public function NbrParType($type){
        $query=$this->getEntityManager()->createQuery("SELECT count(et) FROM MainBundle:Etablissement et WHERE et.type like :no ")
            ->setParameter('no', $type);
        return $query->getScalarResult();
    }

}
