<?php

namespace MainBundle\Repository;

/**
 * EtablissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtablissementRepository extends \Doctrine\ORM\EntityRepository
{
    public function FiltrerDQL($critere)
    {
        $query=$this->getEntityManager()->createQuery("SELECT e FROM MainBundle:Etablissement e WHERE e.type like :typ 
            order by e.nom ASC")
            ->setParameter('typ', '%'.$critere.'%');
        return $query->getResult();
    }

    public function RechercherDQL($nom)
    {
        $query=$this->getEntityManager()->createQuery("SELECT et FROM MainBundle:Etablissement et WHERE et.nom like :no 
            order by et.nom ASC")
            ->setParameter('no', '%'.$nom.'%');
        return $query->getResult();
    }

    public function RechercherCNDQL($nom,$critere)
    {
        $query=$this->getEntityManager()->createQuery("SELECT et FROM MainBundle:Etablissement et WHERE et.nom like :no and et.type like :typ
            order by et.nom ASC")
            ->setParameter('no', '%'.$nom.'%')->setParameter('typ','%'.$critere.'%');
        return $query->getResult();
    }

}
