<?php

namespace MainBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRecent(){

        $em = $this->getEntityManager();
        $currentdate = new \DateTime('now');
        $query = $em->createQuery(
            'SELECT e
        FROM MainBundle:Evenement e
        WHERE e.date >= :date'
        )->setParameter('date', $currentdate);

        return $query->getResult();
    }
    public function findRecentEtab($idEtab){

        $em = $this->getEntityManager();
        $currentdate = new \DateTime('now');
        $query = $em->createQuery(
            'SELECT e
        FROM MainBundle:Evenement e
        WHERE e.date >= :date
        AND e.etablissement = :etab'
        )->setParameter('date', $currentdate)
            ->setParameter('etab', $idEtab);;

        return $query->getResult();
    }
    public function NbrParType($type){
        $query=$this->getEntityManager()->createQuery("SELECT count(ev) FROM MainBundle:Evenement ev WHERE ev.type like :no 
            order by et.nom ASC")
            ->setParameter('no', $type);
        return $query->getScalarResult();
    }

    public function booool($idevent){

        $em = $this->getEntityManager();
        $currentdate = new \DateTime('now');
        $query = $em->createQuery(
            'SELECT e.date > :date
        FROM MainBundle:Evenement e
        WHERE e.id = :id'
        )->setParameter('date', $currentdate)->setParameter('id',$idevent);

        return $query->getResult();
    }
}
