<?php

namespace MainBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{
    public function countFavoris($etabid,$userid){

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT count(f)
        FROM MainBundle:Favoris f
        WHERE f.user = :usr
        AND f.favoris = :fav'
        )->setParameter('usr', $userid)
        ->setParameter('fav',$etabid);

        return $query->getSingleScalarResult();
    }
}
