<?php

namespace MainBundle\Repository;
use MainBundle\Entity\User;

/**
 * GoingEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoingEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function isGoing($event, User $user)
    {
        return
            $this->createQueryBuilder('c')
                ->andWhere('c.user = :user')
                ->andWhere('c.event = :fav')
                ->setParameter('fav', $event)
                ->setParameter('user', $user)
                ->getQuery()->getResult();

    }

    public function countGoingEvent($eventid,$userid){

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT count(f)
        FROM MainBundle:GoingEvent f
        WHERE f.user = :usr
        AND f.event = :ev'
        )->setParameter('usr', $userid)
            ->setParameter('ev',$eventid);

        return $query->getSingleScalarResult();
    }
}
