<?php

namespace MainBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getUnseenNotifications($user)
    {
        // Construct the query (notifications ordered by date)
        $query = "SELECT n FROM MainBundle:Notification n WHERE n.user = ".$user->getId()." AND n.seen = 0 ORDER BY n.date DESC";
        // Execute the query
        $notifications = $this->getEntityManager()->createQuery($query)->getResult();
        // Validate the query
        if($notifications == null || count($notifications) == 0)
            return null;

        return $notifications;
    }

    public function getNotifications($user)
    {
        // Construct the query (notifications ordered by date)
        $query = "SELECT n FROM MainBundleBundle:Notification n WHERE n.user = ".$user->getId()." ORDER BY n.date DESC";
        // Execute the query
        $notifications = $this->getEntityManager()->createQuery($query)->getResult();
        // Validate the query
        if($notifications == null || count($notifications) == 0)
            return null;

        return $notifications;
    }

    public function getNotificationsCount($user)
    {
        // Get all the notifications
        $notifications = $this->getEntityManager()->getRepository("MainBundleBundle:Notification")->findBy(
            array("user"=>$user->getId(), "seen"=>0));

        // Validate the query
        if($notifications == null)
            return 0;

        return count($notifications);
    }
}
