<?php

namespace MainBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function RechercherDQL($nom)
    {
        $query=$this->getEntityManager()->createQuery("SELECT r FROM MainBundle:Reservation r WHERE r.nom like :n 
            order by et.nom ASC")
            ->setParameter('no', '%'.$nom.'%');
        return $query->getResult();
    }
}
