<?php

namespace MainBundle\Repository;

/**
 * RestaurationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurationRepository extends \Doctrine\ORM\EntityRepository
{
}
