<?php

namespace MainBundle\Repository;
use MainBundle\Entity\Etablissement;
use MainBundle\Entity\User;

/**
 * VisitedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedRepository extends \Doctrine\ORM\EntityRepository
{

    public function isVisited($etab, User $user)
    {
        return
            $this->createQueryBuilder('c')
                ->andWhere('c.user = :user')
                ->andWhere('c.favoris = :fav')
                ->setParameter('fav', $etab)
                ->setParameter('user', $user)
                ->getQuery()->getResult();

    }

    public function countVisited($etabid, $userid)
    {

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT count(f)
        FROM MainBundle:Visited f
        WHERE f.user = :usr
        AND f.favoris = :fav'
        )->setParameter('usr', $userid)
            ->setParameter('fav', $etabid);

        return $query->getSingleScalarResult();
    }
}
