<?php

namespace MainBundle\Repository;

/**
 * VisitedEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedEventRepository extends \Doctrine\ORM\EntityRepository
{
}
