<?php

namespace MainBundle\Repository;
use MainBundle\Entity\User;

/**
 * VisitedEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedEventRepository extends \Doctrine\ORM\EntityRepository
{

    public function isVisited($event, User $user)
    {
        return
            $this->createQueryBuilder('c')
                ->andWhere('c.user = :user')
                ->andWhere('c.event = :event')
                ->setParameter('event', $event)
                ->setParameter('user', $user)
                ->getQuery()->getResult();

    }

    public function countVisitedEvent($eventid,$userid){

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT count(f)
        FROM MainBundle:VisitedEvent f
        WHERE f.user = :usr
        AND f.event = :ev'
        )->setParameter('usr', $userid)
            ->setParameter('ev',$eventid);

        return $query->getSingleScalarResult();
    }
}
