<?php

namespace MainBundle\Repository;

/**
 * VisitedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedRepository extends \Doctrine\ORM\EntityRepository
{
}
