<?php

namespace MainBundle\Repository;

/**
 * VisitedEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisitedEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function countVisitedEvent($eventid,$userid){

        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT count(f)
        FROM MainBundle:VisitedEvent f
        WHERE f.user = :usr
        AND f.event = :ev'
        )->setParameter('usr', $userid)
            ->setParameter('ev',$eventid);

        return $query->getSingleScalarResult();
    }
}
