<?php

namespace MainBundle\Repository;

/**
 * WishlisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WishlisteRepository extends \Doctrine\ORM\EntityRepository
{
}
