main_homepage:
    path:     /Home
    defaults: { _controller: MainBundle:Default:index }

main_homepage_admin:
    path:     /HomeAdmin
    defaults: { _controller: MainBundle:Default:indexAdmin }

a_propos:
    path:     /APropos
    defaults: { _controller: MainBundle:Default:apropos }

contact:
    path:     /Contact
    defaults: { _controller: MainBundle:Default:contact }

ajouter_etablissement:
    path:     /AjouterEtablissement
    defaults: { _controller: MainBundle:Etablissement:Ajout }

modifier_etablissement:
    path:     /ModifierEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Modif }

afficher_etablissement:
    path:     /AfficherEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Affiche }

supprimer_etablissement:
    path:     /SupprimerEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Supp }

main_bundle_get_notif:
    path:     /notifications/get
    defaults: { _controller: MainBundle:Notifications:get }

main_bundle_show_notif:
    path:     /notifications/show
    defaults: { _controller: MainBundle:Notifications:show }
