main_homepage:
    path:     /Home
    defaults: { _controller: MainBundle:Default:index }

main_homepage_admin:
    path:     /HomeAdmin
    defaults: { _controller: MainBundle:Default:indexAdmin }

a_propos:
    path:     /APropos
    defaults: { _controller: MainBundle:Default:apropos }

contact:
    path:     /Contact
    defaults: { _controller: MainBundle:Default:contact }

Ajouter_Etablissement_Admin:
    path:     /AjouterEtablissementAdmin
    defaults: { _controller: MainBundle:Etablissement:Ajout }

Afficher_Etablissement_Admin:
    path:     /AfficherEtablissementAdmin
    defaults: { _controller: MainBundle:Etablissement:Affiche }

Modifier_Etablissement_Admin:
    path:     /ModifierEtablissementAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:Modif }

Afficher_Etablissement_ParId_Admin:
    path:     /AfficherEtablissementParIdAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:AfficheId }

Supprimer_Etablissement_Admin:
    path:     /SupprimerEtablissementAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:Supp }

Modifier_Etablissement_Photo_Admin:
    path:     /ModifierEtablissementPhotoAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:ModifPhoto }

Filtrer_Etablissement:
    path:     /FiltrerEtablissement/{critere}
    defaults: { _controller: MainBundle:Etablissement:Filtre }

Trier_Etablissement:
    path:     /TrierEtablissement/{critere}
    defaults: { _controller: MainBundle:Etablissement:Tri }

Rechercher_Etablissement:
    path:     /RechercherEtablissement
    defaults: { _controller: MainBundle:Etablissement:Recherche }

Ajouter_Etablissement_Client:
    path:     /AjouterEtablissementClient
    defaults: { _controller: MainBundle:Etablissement:AjoutC }

Afficher_Etablissement_Client:
    path:     /AfficherEtablissementClient/{id}
    defaults: { _controller: MainBundle:Etablissement:AfficheC }

Rechercher_Etablissement_Client:
    path:     /RechercherEtablissementClient/{critere}
    defaults: { _controller: MainBundle:Etablissement:RechercherC }

Trier_Etablissement_Client:
    path:     /TrierEtablissementClient/{critere1}/{critere2}
    defaults: { _controller: MainBundle:Etablissement:TriC }

Rechercher_Etablissement_Nom:
    path:     /RechercherEtablissementNom/{critere2}
    defaults: { _controller: MainBundle:Etablissement:RechercheCN }

Ajouter_Tag_Representant:
    path:     /AjouterTag/{id}
    defaults: { _controller: MainBundle:Tag:Ajout }

Supprimer_Tag_Representant:
    path:     /SupprimerTag/{id}/{id1}
    defaults: { _controller: MainBundle:Tag:Supp }

Rechercher_Etablissement_Tag:
    path:     /RechercherEtablissementTag/{tag}
    defaults: { _controller: MainBundle:Etablissement:RechercheT }

modifier_etablissement:
    path:     /ModifierEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Modif }

supprimer_etablissement:
    path:     /SupprimerEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Supp }

main_bundle_get_notif:
    path:     /notifications/get
    defaults: { _controller: MainBundle:Notifications:get }

main_bundle_show_notif:
    path:     /notifications/show
    defaults: { _controller: MainBundle:Notifications:show }

ajout_reservation:
    path:     /AjoutRes{id1}/{id2}
    defaults: { _controller: MainBundle:Reservation:Ajout }

affiche_reservation:
    path:     /AfficheRes
    defaults: { _controller: MainBundle:Reservation:Affiche }

delete_reservation:
    path:     /DeleteRes{id1}/{id2}
    defaults: { _controller: MainBundle:Reservation:Delete }

update_reservation:
    path:     /UpdateRes{id1}/{id2}
    defaults: { _controller: MainBundle:Reservation:Update }

ajout_experience:
    path:     /AjoutEx
    defaults: { _controller: MainBundle:SharedExperience:Ajout }

delete_experience:
    path:     /DeleteEx
    defaults: { _controller: MainBundle:SharedExperience:Delete }

update_experience:
    path:     /UpdateEx
    defaults: { _controller: MainBundle:SharedExperience:Update }

affiche_experience:
    path:     /AfficheEx
    defaults: { _controller: MainBundle:SharedExperience:Affiche }
