main_homepage:
    path:     /Home
    defaults: { _controller: MainBundle:Default:index }

main_homepage_admin:
    path:     /HomeAdmin
    defaults: { _controller: MainBundle:Default:indexAdmin }

a_propos:
    path:     /APropos
    defaults: { _controller: MainBundle:Default:apropos }

contact:
    path:     /Contact
    defaults: { _controller: MainBundle:Default:contact }



_ajout:
    path:     /AjoutRes
    defaults: { _controller: MainBundle:Reservation:Ajout }

_update:
    path:     /UpdateRes
    defaults: { _controller: MainBundle:Reservation:Update }

_delete:
    path:     /DeleteRes
    defaults: { _controller: MainBundle:Reservation:Delete }

_affiche:
    path:     /AfficheRes
    defaults: { _controller: MainBundle:Reservation:Affiche }
