main_homepage:
    path:     /Home
    defaults: { _controller: MainBundle:Default:index }

main_homepage_admin:
    path:     /HomeAdmin
    defaults: { _controller: MainBundle:Default:indexAdmin }

a_propos:
    path:     /APropos
    defaults: { _controller: MainBundle:Default:apropos }

contact:
    path:     /Contact
    defaults: { _controller: MainBundle:Default:contact }


ajouter_etablissement:
    path:     /AjouterEtablissement
    defaults: { _controller: MainBundle:Etablissement:Ajout }

_ajout:
    path:     /AjoutRes
    defaults: { _controller: MainBundle:Reservation:Ajout }

Ajouter_Etablissement_Admin:
    path:     /AjouterEtablissementAdmin
    defaults: { _controller: MainBundle:Etablissement:Ajout }

Afficher_Etablissement_Admin:
    path:     /AfficherEtablissementAdmin
    defaults: { _controller: MainBundle:Etablissement:Affiche }

Modifier_Etablissement_Admin:
    path:     /ModifierEtablissementAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:Modif }

Afficher_Etablissement_ParId_Admin:
    path:     /AfficherEtablissementParIdAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:AfficheId }

Afficher_Etablissement_user:
    path:     /etab/{id}
    defaults: { _controller: MainBundle:Etablissement:AfficheUser }


Afficher_Evenement_Admin:
    path:     /AfficherEvenementParAdmin
    defaults: { _controller: MainBundle:Evenement:AfficheAdmin }

Afficher_Evenement_ParId_Admin:
    path:     /AfficherEvenementParAdmin/{id}
    defaults: { _controller: MainBundle:Evenement:AfficheAdminId}

Afficher_Evenement_ParId_Admin_etab:
    path:     /AfficherEvenementParAdminEtab/{id_etab}
    defaults: { _controller: MainBundle:Evenement:AfficheEtab}

Supprimer_Etablissement_Admin:
    path:     /SupprimerEtablissementAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:Supp }

Supprimer_Evenement_Admin:
    path:     /SupprimerEvenementtAdmin/{id}
    defaults: { _controller: MainBundle:Evenement:RemoveAdmin }

Modifier_Etablissement_Photo_Admin:
    path:     /ModifierEtablissementPhotoAdmin/{id}
    defaults: { _controller: MainBundle:Etablissement:ModifPhoto }

Filtrer_Etablissement:
    path:     /FiltrerEtablissement/{critere}
    defaults: { _controller: MainBundle:Etablissement:Filtre }

Trier_Etablissement:
    path:     /TrierEtablissement/{critere}
    defaults: { _controller: MainBundle:Etablissement:Tri }

Rechercher_Etablissement:
    path:     /RechercherEtablissement
    defaults: { _controller: MainBundle:Etablissement:Recherche }

Ajouter_Etablissement_Client:
    path:     /AjouterEtablissementClient
    defaults: { _controller: MainBundle:Etablissement:AjoutC }

Ajouter_Etablissement:
    path:     /AjouterEtablissement
    defaults: { _controller: MainBundle:Etablissement:Ajout }

modifier_etablissement:
    path:     /ModifierEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Modif }

afficher_etablissement:
    path:     /AfficherEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Affiche }

supprimer_etablissement:
    path:     /SupprimerEtablissement/{id}
    defaults: { _controller: MainBundle:Etablissement:Supp }


_update:
    path:     /UpdateRes
    defaults: { _controller: MainBundle:Reservation:Update }

_delete:
    path:     /DeleteRes
    defaults: { _controller: MainBundle:Reservation:Delete }

_affiche:
    path:     /AfficheRes
    defaults: { _controller: MainBundle:Reservation:Affiche }


all_events:
    path:     /events
    defaults: { _controller: MainBundle:Evenement:afficheall }

show_event:
    path:     /event/{id_event}
    defaults: { _controller: MainBundle:Evenement:Affiche }

etab_events:
    path:     /eventsEtab/{id_etab}
    defaults: { _controller: MainBundle:Evenement:AfficheEtab }

update_event:
    path:     /eventUpdate/{id}
    defaults: { _controller: MainBundle:Evenement:Update }

delete_event:
    path:     /eventDelete/{id}
    defaults: { _controller: MainBundle:Evenement:Remove }

add_event:
    path:     /eventAdd/{id_etab}
    defaults: { _controller: MainBundle:Evenement:Ajout }



ajouter_wish:
    path:     /AjouterWish/{id}
    defaults: { _controller: MainBundle:Wishlist:Ajout }

delete_wish:
      path:     /RetirerWish/{id_etablissement}
      defaults: { _controller: MainBundle:Wishlist:Remove }

affiche_wish:
      path:     /VoirWish
      defaults: { _controller: MainBundle:Wishlist:Affiche }

ajouter_visited:
    path:     /AjouterVisited/{id}
    defaults: { _controller: MainBundle:Visited:AjoutVisited }

delete_visited:
      path:     /RetirerVisited/{id_etablissement}
      defaults: { _controller: MainBundle:Visited:RemoveVisited }

delete_going_event:
      path:     /RetirerVisitedEvent/{id_event}
      defaults: { _controller: MainBundle:Visited:RemoveGoingEvent }

delete_interest_event:
      path:     /RetirerInterestEvent/{id_event}
      defaults: { _controller: MainBundle:Visited:RemoveInterestedEvent }

affiche_visited:
      path:     /VoirVisited
      defaults: { _controller: MainBundle:Visited:AfficheVisited }

affiche_going_event:
      path:     /VoirVisited
      defaults: { _controller: MainBundle:Visited:AfficheGoingEvent }

ajouter_going_event:
    path:     /AjouterGoingEvent/{id}
    defaults: { _controller: MainBundle:Visited:AjoutGoingEvent }

ajouter_interest_event:
    path:     /AjouterInterestEvent/{id}
    defaults: { _controller: MainBundle:Visited:AjoutInterestEvent }


affiche_intrested_event:
      path:     /VoirVisited
      defaults: { _controller: MainBundle:Visited:AfficheInterestEvent }

all_offre:
    path:     /offres
    defaults: { _controller: MainBundle:Offre:afficheall }

etab_offre:
    path:     /offresEtab/{id_etab}
    defaults: { _controller: MainBundle:Offre:Affiche }

update_offre:
    path:     /offreUpdate/{id}
    defaults: { _controller: MainBundle:Offre:Update }

delete_offre:
    path:     /offreDelete/{id}
    defaults: { _controller: MainBundle:Offre:Remove }

add_offre:
    path:     /offreAdd/{id_etab}
    defaults: { _controller: MainBundle:Offre:Ajout }

