main_homepage:
    path:     /Home
    defaults: { _controller: MainBundle:Default:index }

main_homepage_admin:
    path:     /HomeAdmin
    defaults: { _controller: MainBundle:Default:indexAdmin }

a_propos:
    path:     /APropos
    defaults: { _controller: MainBundle:Default:apropos }

contact:
    path:     /Contact
    defaults: { _controller: MainBundle:Default:contact }

<<<<<<< HEAD
ajouter_etablissement:
    path:     /AjouterEtablissement
    defaults: { _controller: MainBundle:Etablissement:Ajout }

=======
main_bundle_get_notif:
    path:     /notifications/get
    defaults: { _controller: MainBundle:Notifications:get }
>>>>>>> 4871a2adc786c4f28433e34b776349e2c19ad793

main_bundle_show_notif:
    path:     /notifications/show
    defaults: { _controller: MainBundle:Notifications:show }
